"""
Generated by following the FIXED PROMPT A verbatim (ui/pages/plugin_guide.py,
Step 1b, post Plan-Phase-2). Prompt A now explicitly asks for: HARDWARE_NAME/
HARDWARE_TYPE constants, get_info()/get_status()/get_clients() with no
required positional args, a keyring-backed credential (never hard-coded),
timeout=10 on every request, and every exception classified as
AUTH:/NET:/DEPS:/ERR: via extra.error rather than allowed to propagate.

See tests/test_ai_prompt_pipeline.py for the resulting (now-passing)
validation and runtime assertions -- compare with git history for the
pre-fix version of this same fixture, which was not a valid plugin at all.

pip install requests keyring
"""
import json
import sys

import requests

HARDWARE_NAME = "Netgear Nighthawk"
HARDWARE_TYPE = "router"
HARDWARE_IP   = "192.168.1.1"


def _load_password() -> str:
    ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    try:
        import keyring
        pw = keyring.get_password("NetSentinel/hardware", ip)
        if pw:
            return pw
    except Exception:
        pass  # keyring backend unavailable — fall through to RuntimeError below
    raise RuntimeError(f"No password saved for {ip}. Save it in the Hardware Integration page.")


def _fmt_err(exc: Exception) -> str:
    msg = str(exc)
    if isinstance(exc, ImportError) or "pip install" in msg:
        return "DEPS: " + msg
    # Check exception type / HTTP status before message keywords: a raw
    # ConnectionError's message includes the request URL, so a path like
    # /api/login would otherwise misclassify a connection failure as AUTH.
    status = getattr(getattr(exc, "response", None), "status_code", None)
    if status in (401, 403):
        return "AUTH: " + msg
    if any(w in type(exc).__name__ for w in ("Connection", "Timeout")):
        return "NET: " + msg
    lm = msg.lower()
    if any(w in lm for w in ("refused", "timed out", "unreachable", "no route", "network is")):
        return "NET: " + msg
    if any(w in lm for w in ("auth", "password", "login", "401", "forbidden", "wrong credential")):
        return "AUTH: " + msg
    return "ERR: " + msg


def _login() -> str:
    ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    pw = _load_password()
    resp = requests.post(f"http://{ip}/api/login", json={"password": pw}, timeout=10)
    resp.raise_for_status()
    return resp.json()["token"]


def get_info() -> dict:
    ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    return {"name": HARDWARE_NAME, "type": HARDWARE_TYPE, "ip": ip}


def get_status() -> dict:
    ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    try:
        token = _login()
        resp = requests.get(
            f"http://{ip}/api/status", headers={"Authorization": f"Bearer {token}"}, timeout=10
        )
        resp.raise_for_status()
        data = resp.json()
        return {
            "wan_ip":            data.get("wan_ip"),
            "uptime_sec":        data.get("uptime_sec"),
            "connected_clients": len(data.get("clients", [])),
            "extra": {},
        }
    except Exception as exc:
        return {
            "wan_ip": None, "uptime_sec": None, "connected_clients": None,
            "extra": {"error": _fmt_err(exc)},
        }


def get_clients() -> list:
    ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    try:
        token = _login()
        resp = requests.get(
            f"http://{ip}/api/status", headers={"Authorization": f"Bearer {token}"}, timeout=10
        )
        resp.raise_for_status()
        data = resp.json()
        return [
            {"ip": c["ip"], "mac": c["mac"], "hostname": c["name"]}
            for c in data.get("clients", [])
        ]
    except Exception:
        return []


if __name__ == "__main__" and "--netsentinel" not in sys.argv:
    print(json.dumps(
        {"info": get_info(), "status": get_status(), "clients": get_clients()},
        indent=2,
    ))

import sys as _sys
if "--netsentinel" in _sys.argv:
    import json as _json
    _sys.stdout.write(_json.dumps({
        "info":    get_info(),
        "status":  get_status(),
        "clients": get_clients(),
    }, default=str) + "\n")
    _sys.exit(0)
