"""
Generated by handing the (post-Plan-Phase-2, upgraded) wizard/guide _TEMPLATE
(ui/widgets/hub_helpers.py _TEMPLATE) to an AI with the FIXED "PROMPT -- Ask
AI to complete the template" text (ui/pages/plugin_guide.py Step 2), which now
explicitly says: complete get_info()/get_status()/get_clients() only, and
keep _load_password(), the _fmt_err() error-prefix helper, the try/except
structure, and the standalone-test/shim blocks exactly as-is, using
timeout=10 on every request.

Since _TEMPLATE itself now ships _fmt_err() and a try/except around
get_status()'s body, an AI that follows the instruction literally inherits
correct error classification for free -- unlike the pre-fix fixture (see git
history), which was correct on keyring/instance-IP but still hit the
unclassified-error defect because the base template itself lacked _fmt_err.
See tests/test_ai_prompt_pipeline.py.
"""

import json
import sys

import requests

# ── Metadata (required) ───────────────────────────────────────────────────────
HARDWARE_NAME = "Asus RT-AX88U"      # displayed in the app
HARDWARE_TYPE = "router"             # router | modem | ap | switch | other
HARDWARE_IP   = "192.168.1.1"        # your device's LAN address
USERNAME      = "admin"


# ── Credentials (read from OS keychain — never hard-code passwords) ───────────

def _load_password() -> str:
    """Return the saved admin password from the OS keychain."""
    _ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    try:
        import keyring
        _iid = globals().get("_NETSENTINEL_INSTANCE_ID") or ""
        pw = None
        if _iid:
            pw = keyring.get_password("NetSentinel/plugin", _iid)
        if not pw:
            pw = keyring.get_password("NetSentinel/hardware", _ip)
        if pw:
            return pw
    except Exception:
        pass  # keyring backend unavailable or OS error — caller's RuntimeError below explains the fix
    raise RuntimeError(
        f"No password saved for {_ip}. "
        "Enter and save the password in the Hardware Integration page."
    )


# ── Error classification (kept exactly as the template provides it) ───────────

def _fmt_err(exc: Exception) -> str:
    msg = str(exc)
    if isinstance(exc, ImportError) or "pip install" in msg:
        return "DEPS: " + msg
    status = getattr(getattr(exc, "response", None), "status_code", None)
    if status in (401, 403):
        return "AUTH: " + msg
    if any(w in type(exc).__name__ for w in ("Connection", "Timeout")):
        return "NET: " + msg
    lm = msg.lower()
    if any(w in lm for w in ("refused", "timed out", "unreachable", "no route", "network is")):
        return "NET: " + msg
    if any(w in lm for w in ("auth", "password", "login", "401", "forbidden", "wrong credential")):
        return "AUTH: " + msg
    return "ERR: " + msg


def _login() -> str:
    ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    pw = _load_password()
    resp = requests.post(f"http://{ip}/api/login", json={"password": pw}, timeout=10)
    resp.raise_for_status()
    return resp.json()["token"]


# ── Required interface ────────────────────────────────────────────────────────

def get_info() -> dict:
    """Static metadata — called once when the script is first imported."""
    ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    return {
        "name":         HARDWARE_NAME,
        "type":         HARDWARE_TYPE,
        "ip":           ip,
        "manufacturer": "Asus",
        "model":        "RT-AX88U",
        "firmware":     "v1.0.0",
    }


def get_status(config=None) -> dict:
    """Live status — called periodically when the page is visible."""
    ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    try:
        token = _login()
        resp = requests.get(
            f"http://{ip}/api/status", headers={"Authorization": f"Bearer {token}"}, timeout=10
        )
        resp.raise_for_status()
        data = resp.json()
        return {
            "wan_ip":            data.get("wan_ip"),
            "uptime_sec":        data.get("uptime_sec"),
            "download_mbps":     None,
            "upload_mbps":       None,
            "signal_dbm":        None,
            "connected_clients": len(data.get("clients", [])),
            "mesh_nodes":        1,
            "extra": {
                "nodes": [
                    {"name": HARDWARE_NAME, "mac": "", "ip": ip, "role": "primary"},
                ],
            },
        }
    except Exception as exc:
        return {
            "wan_ip": None, "uptime_sec": None,
            "download_mbps": None, "upload_mbps": None,
            "signal_dbm": None, "connected_clients": None,
            "extra": {"error": _fmt_err(exc)},
        }


# ── Optional interface ────────────────────────────────────────────────────────

def get_clients() -> list:
    """Return connected devices."""
    ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    try:
        token = _login()
        resp = requests.get(
            f"http://{ip}/api/status", headers={"Authorization": f"Bearer {token}"}, timeout=10
        )
        resp.raise_for_status()
        data = resp.json()
        return [
            {"ip": c["ip"], "mac": c["mac"], "hostname": c["name"],
             "unit": HARDWARE_NAME, "band": "5G"}
            for c in data.get("clients", [])
        ]
    except Exception:
        return []


# ── Standalone test ───────────────────────────────────────────────────────────
if __name__ == "__main__" and "--netsentinel" not in sys.argv:
    print("=== Hardware Info ===")
    print(json.dumps(get_info(), indent=2, default=str))
    print("\n=== Live Status ===")
    print(json.dumps(get_status(), indent=2, default=str))
    print("\n=== Clients ===")
    print(json.dumps(get_clients(), indent=2, default=str))

# ── NetSentinel plugin shim (manual standalone test hook — do not remove) ─────
import sys as _sys
if "--netsentinel" in _sys.argv:
    import json as _json
    try:
        _clients = get_clients()
    except NameError:
        _clients = []
    _sys.stdout.write(_json.dumps({
        "info":    get_info(),
        "status":  get_status(),
        "clients": _clients,
    }, default=str) + "\n")
    _sys.exit(0)
