"""
modules/digest_builder.py — Weekly digest email generator (SCHED-4).

Builds a self-contained HTML email summarising the past 7 days:
  • Network health grade + score
  • Top 5 alerts by frequency
  • New devices joined
  • CVE count
  • Uptime % summary
"""
from __future__ import annotations

import datetime
import html
import time
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from modules.metric_store import MetricStore


_STYLE = """
body { margin:0; padding:0; background:#F4F4F4; font-family: -apple-system, BlinkMacSystemFont,
       'Segoe UI', Roboto, Arial, sans-serif; color:#1A1A2E; }
.wrapper { max-width:640px; margin:0 auto; background:#FFFFFF; }
.header { background:#1A3A5C; padding:24px 32px; }
.header h1 { margin:0; font-size:22px; font-weight:700; color:#FFFFFF; }
.header p  { margin:4px 0 0; font-size:12px; color:#9BA8B4; }
.section { padding:20px 32px; border-bottom:1px solid #ECECEC; }
.section h2 { margin:0 0 12px; font-size:14px; font-weight:700;
              color:#1A3A5C; text-transform:uppercase; letter-spacing:.5px; }
.kpi-row { display:flex; gap:12px; flex-wrap:wrap; margin-bottom:8px; }
.kpi { flex:1; min-width:120px; background:#F4F4F4; border:1px solid #D4D4D4;
       border-left:3px solid #1A3A5C; padding:10px 14px; }
.kpi .label { font-size:9px; font-weight:700; color:#6B7280; text-transform:uppercase;
              letter-spacing:.5px; margin-bottom:4px; }
.kpi .value { font-size:26px; font-weight:700; color:#1A1A2E; }
.kpi.green  { border-left-color:#10B981; } .kpi.green .value  { color:#065F46; }
.kpi.amber  { border-left-color:#F59E0B; } .kpi.amber .value  { color:#92400E; }
.kpi.red    { border-left-color:#EF4444; } .kpi.red .value    { color:#991B1B; }
table { width:100%; border-collapse:collapse; font-size:12px; }
th { background:#1A3A5C; color:#FFFFFF; padding:6px 10px; text-align:left;
     font-size:10px; font-weight:700; text-transform:uppercase; }
td { padding:5px 10px; border-bottom:1px solid #ECECEC; }
tr:nth-child(even) td { background:#F9F9F9; }
.up   { color:#065F46; font-weight:600; }
.warn { color:#92400E; font-weight:600; }
.down { color:#991B1B; font-weight:600; }
.footer { padding:16px 32px; font-size:10px; color:#9BA8B4; text-align:center; }
"""


def build_digest_html(store: "MetricStore") -> str:
    """Return a fully self-contained HTML weekly digest string."""
    now       = datetime.datetime.now()
    week_ago  = now - datetime.timedelta(days=7)
    ts_range  = f"{week_ago.strftime('%b %d')} – {now.strftime('%b %d, %Y')}"

    grade_row  = _grade_kpi(store)
    alert_kpi  = _alert_kpi(store)
    device_kpi = _new_device_kpi(store)
    cve_kpi    = _cve_kpi(store)
    alert_tbl  = _top_alerts_table(store)
    device_tbl = _new_devices_table(store)
    uptime_tbl = _uptime_table(store)

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>NetSentinel Weekly Digest</title>
<style>{_STYLE}</style>
</head><body>
<div class="wrapper">
  <div class="header">
    <h1>NetSentinel Weekly Digest</h1>
    <p>{ts_range}</p>
  </div>

  <div class="section">
    <h2>Network Health</h2>
    <div class="kpi-row">
      {grade_row}
      {alert_kpi}
      {device_kpi}
      {cve_kpi}
    </div>
  </div>

  <div class="section">
    <h2>Top Alerts (last 7 days)</h2>
    {alert_tbl}
  </div>

  <div class="section">
    <h2>New Devices</h2>
    {device_tbl}
  </div>

  <div class="section">
    <h2>Device Uptime</h2>
    {uptime_tbl}
  </div>

  <div class="footer">
    Generated by NetSentinel on {now.strftime('%Y-%m-%d %H:%M')} &mdash;
    <a href="https://github.com/ossianericson/netsentinel" style="color:#1A3A5C;">netsentinel</a>
  </div>
</div>
</body></html>"""


# ── KPI tiles ─────────────────────────────────────────────────────────────────

def _grade_kpi(store: "MetricStore") -> str:
    try:
        row = store.get_grade_result()
        if row:
            grade = row.get("grade", "—")
            score = row.get("score", 0)
            color = "green" if score >= 80 else ("amber" if score >= 60 else "red")
            return (
                f'<div class="kpi {color}">'
                f'<div class="label">Grade</div>'
                f'<div class="value">{html.escape(str(grade))}</div>'
                f'</div>'
            )
    except Exception:
        pass
    return '<div class="kpi"><div class="label">Grade</div><div class="value">—</div></div>'


def _alert_kpi(store: "MetricStore") -> str:
    try:
        alerts = store.get_recent_alerts(hours=168, limit=5000)
        count  = len(alerts)
        color  = "red" if count > 20 else ("amber" if count > 5 else "green")
        return (
            f'<div class="kpi {color}">'
            f'<div class="label">Alerts</div>'
            f'<div class="value">{count}</div>'
            f'</div>'
        )
    except Exception:
        return '<div class="kpi"><div class="label">Alerts</div><div class="value">—</div></div>'


def _new_device_kpi(store: "MetricStore") -> str:
    try:
        events = store.query_device_events(hours=168)
        joins  = sum(1 for e in events if e.event_type in ("join", "new"))
        color  = "amber" if joins > 0 else "green"
        return (
            f'<div class="kpi {color}">'
            f'<div class="label">New Devices</div>'
            f'<div class="value">{joins}</div>'
            f'</div>'
        )
    except Exception:
        return '<div class="kpi"><div class="label">New Devices</div><div class="value">—</div></div>'


def _cve_kpi(store: "MetricStore") -> str:
    try:
        cves  = store.list_cve_lifecycles() or []
        count = len(cves)
        color = "red" if count > 0 else "green"
        return (
            f'<div class="kpi {color}">'
            f'<div class="label">CVEs</div>'
            f'<div class="value">{count}</div>'
            f'</div>'
        )
    except Exception:
        return '<div class="kpi"><div class="label">CVEs</div><div class="value">—</div></div>'


# ── Tables ────────────────────────────────────────────────────────────────────

def _top_alerts_table(store: "MetricStore") -> str:
    try:
        alerts = store.get_recent_alerts(hours=168, limit=5000)
        if not alerts:
            return "<p style='color:#9BA8B4;font-size:12px'>No alerts in the last 7 days.</p>"
        from collections import Counter
        counts = Counter(a.get("rule_name", "Unknown") for a in alerts)
        rows = ""
        for rule, n in counts.most_common(5):
            rows += f"<tr><td>{html.escape(rule)}</td><td>{n}</td></tr>"
        return (
            "<table><thead><tr><th>Rule</th><th>Count</th></tr></thead>"
            f"<tbody>{rows}</tbody></table>"
        )
    except Exception:
        return "<p style='color:#9BA8B4;font-size:12px'>Alert data unavailable.</p>"


def _new_devices_table(store: "MetricStore") -> str:
    try:
        events = store.query_device_events(hours=168)
        joins  = [e for e in events if e.event_type in ("join", "new")]
        if not joins:
            return "<p style='color:#9BA8B4;font-size:12px'>No new devices joined this week.</p>"
        rows = ""
        for e in joins[:10]:
            ts  = datetime.datetime.fromtimestamp(e.ts).strftime("%a %H:%M")
            rows += (
                f"<tr><td>{html.escape(e.ip or '—')}</td>"
                f"<td>{html.escape(e.mac or '—')}</td>"
                f"<td>{ts}</td></tr>"
            )
        return (
            "<table><thead><tr><th>IP</th><th>MAC</th><th>When</th></tr></thead>"
            f"<tbody>{rows}</tbody></table>"
        )
    except Exception:
        return "<p style='color:#9BA8B4;font-size:12px'>Device data unavailable.</p>"


def _uptime_table(store: "MetricStore") -> str:
    try:
        rows = store.query_uptime_table()
        if not rows:
            return "<p style='color:#9BA8B4;font-size:12px'>No uptime data recorded yet.</p>"
        tbl_rows = ""
        for r in rows[:10]:
            pct = r.get("168.0", r.get("24.0", 100.0))
            cls = "up" if pct >= 99 else ("warn" if pct >= 95 else "down")
            tbl_rows += (
                f"<tr><td>{html.escape(r['ip'])}</td>"
                f"<td>{html.escape(r.get('hostname') or '—')}</td>"
                f'<td class="{cls}">{pct:.1f}%</td></tr>'
            )
        return (
            "<table><thead><tr><th>IP</th><th>Hostname</th><th>7-Day Uptime</th></tr></thead>"
            f"<tbody>{tbl_rows}</tbody></table>"
        )
    except Exception:
        return "<p style='color:#9BA8B4;font-size:12px'>Uptime data unavailable.</p>"
