# -*- mode: python ; coding: utf-8 -*-
"""
NetSentinel — PyInstaller build specification.

This is the SINGLE SOURCE OF TRUTH for the packaged executable.
Edit this file when adding new modules or dependencies.
build.bat and .github/workflows/release.yml both reference it so
changes propagate to all platforms automatically.

Build (production, windowed):
    pyinstaller NetSentinel.spec

Debug build (keeps a console window so print/traceback output is visible):
    set NETSENTINEL_DEBUG=1 && pyinstaller NetSentinel.spec   (Windows)
    NETSENTINEL_DEBUG=1 pyinstaller NetSentinel.spec           (macOS/Linux)
"""

import os
import sys
from PyInstaller.utils.hooks import collect_all

# ── Build mode ────────────────────────────────────────────────────────────────
# Set NETSENTINEL_DEBUG=1 to get a console window for troubleshooting.
_debug_build = os.environ.get("NETSENTINEL_DEBUG", "0") == "1"

# ── Data files ────────────────────────────────────────────────────────────────
datas = [
    ("offenders.json", "."),
    ("assets/icons", "assets/icons"),
    ("assets/js",    "assets/js"),
    ("ui/assets", "ui/assets"),
    ("data/catalogue.json",   "data"),
    ("data/glossary.json",    "data"),
    ("data/service_map.json", "data"),
    ("plugins/zte_plugin.py", "plugins"),
    ("plugins/deco_plugin.py", "plugins"),
    ("plugins/fritzbox_plugin.py", "plugins"),
    ("plugins/unifi_plugin.py", "plugins"),
    ("plugins/asus_plugin.py", "plugins"),
    ("plugins/netgear_plugin.py", "plugins"),
    ("plugins/mikrotik_plugin.py", "plugins"),
    ("plugins/openwrt_plugin.py", "plugins"),
    ("plugins/synology_plugin.py", "plugins"),
    ("plugins/ha_plugin.py", "plugins"),
]

# ── Collect whole packages (data + binaries + submodule tree) ─────────────────
# PyInstaller cannot auto-discover dynamically-loaded backends and lazy-loaded
# protocol layers, so we collect every file for these packages.
binaries: list = []
hiddenimports: list = [
    # PyQt6 Qt modules that are loaded at runtime via dynamic dispatch
    "PyQt6.sip",
    "PyQt6.QtCore",
    "PyQt6.QtWidgets",
    "PyQt6.QtGui",
    "PyQt6.QtNetwork",
    "PyQt6.QtPrintSupport",
    "PyQt6.QtSvg",
    "PyQt6.QtOpenGL",
    "PyQt6.QtOpenGLWidgets",
    # PyQt6-WebEngine — lazy-imported in network_map_page; must be explicit so
    # PyInstaller's hook-PyQt6.QtWebEngineWidgets.py fires and bundles
    # QtWebEngineProcess.exe, .pak resources, ICU data and locale files.
    "PyQt6.QtWebEngineWidgets",
    "PyQt6.QtWebEngineCore",
    "PyQt6.QtWebChannel",
    # Matplotlib backend used by ui/live_graph.py
    "matplotlib.backends.backend_qtagg",
    # Scapy loads all protocol layers lazily; collect them explicitly
    "scapy.layers.all",
    "scapy.arch.windows",
    # speedtest-cli
    "speedtest",
    # psutil (process/network stats)
    "psutil",
    "psutil._pswindows",
    # keyring platform backends
    "keyring",
    "keyring.backends.Windows",
    "keyring.backends.fail",
    # Flask and dependencies (REST API)
    "flask",
    "flask.json",
    "werkzeug",
    "werkzeug.serving",
    "werkzeug.routing",
    "jinja2",
    "click",
    "itsdangerous",
    # ── modules/ — every backend module listed explicitly ─────────────────────
    "modules.alert_baseline",
    "modules.alert_engine",
    "modules.alert_engine_checks",
    "modules.alert_pattern_detector",
    "modules.alert_suppressor",
    "modules.alert_types",
    "modules.quiet_notifier",
    "modules.morning_briefing",
    "modules.weekly_report",
    "modules.app_traffic_classifier",
    "modules.cdn_ranges",
    "modules.traffic_insights",
    "modules.service_bandwidth_overlay",
    "modules.health_score",
    "modules.isp_vs_router_test",
    "modules.arp_monitor",
    "modules.availability_monitor",
    "modules.bandwidth_monitor",
    "modules.cert_monitor",
    "modules.cloud_metadata",
    "modules.colours",
    "modules.combined_discovery",
    "modules.config_baseline",
    "modules.credentialed_scan",
    "modules.credentialed_scan_helpers",
    "modules.cve_lookup",
    "modules.deco_client",
    "modules.device_classifier",
    "modules.device_types",
    "modules.device_health_summary",
    "modules.device_naming",
    "modules.device_stability",
    "modules.device_tracker",
    "modules.dhcp_detector",
    "modules.dhcp_fingerprint",
    "modules.dhcp_lease_scanner",
    "modules.dns_correlator",
    "modules.dns_zone_scanner",
    "modules.ha_detector",
    "modules.internet_exposure",
    "modules.iot_baseline",
    "modules.log_chart",
    "modules.mac_lookup",
    "modules.mac_registry",
    "modules.maintenance_window",
    "modules.metric_store",
    "modules.metric_store_schema",
    "modules.metric_store_queries",
    "modules.metric_store_queries_uptime",
    "modules.metric_store_queries_metrics",
    "modules.name_resolver",
    "modules.network_benchmark",
    "modules.network_diagnostics",
    "modules.network_log_writer",
    "modules.network_logger",
    "modules.network_map_cache",
    "modules.network_segments",
    "modules.topology_cytoscape",
    "modules.topology_cytoscape_html",
    "modules.topology_cytoscape_style",
    "modules.topology_layout",
    "modules.topology_layouts",
    "modules.topology_snapshot",
    "modules.nl_query",
    "modules.notification_channels",
    "modules.notification_router",
    "modules.nspkg",
    "modules.os_fingerprint",
    "modules.plugin_system",
    "modules.plugin_tools",
    "modules.port_scanner",
    "modules.private_endpoint_checker",
    "modules.process_monitor",
    "modules.report_exporter",
    "modules.report_isp",
    "modules.report_html",
    "modules.report_pdf",
    "modules.report_scheduler",
    "modules.rest_api",
    "modules.risk_scorer",
    "modules.rogue_device",
    "modules.diagnostic_card",
    "modules.lab_scenarios",
    "modules.root_cause_correlator",
    "modules.scheduler",
    "modules.service_monitor",
    "modules.service_diagnostics",
    "modules.service_diagnostics_probes",
    "modules.service_escalation",
    "modules.proactive_digest",
    "modules.smb_enumerator",
    "modules.snmp_poller",
    "modules.snmp_trap_receiver",
    "modules.firewall_rules",
    "modules.service_mapper",
    "modules.scan_status_md",
    "modules.speed_drop_detector",
    "modules.speed_tester",
    "modules.speed_tester_backends",
    "modules.speed_tester_servers",
    "modules.storm_analyser",
    "modules.stp_detector",
    "modules.syn_scanner",
    "modules.syslog_receiver",
    "modules.threat_intel",
    "modules.tls_checker",
    "modules.trend_analyser",
    "modules.hw_detect",
    "modules.network_infrastructure",
    "modules.utils",
    "modules.utils_net",
    "modules.utils_platform",
    "modules.wifi_heatmap",
    "modules.wifi_scanner",
    # ── ui/ — shell and all page modules ──────────────────────────────────────
    "ui.dashboard",
    "ui.scan_wiring",
    "ui.scan_enrichment",
    "ui.header",
    "ui.tabs",
    "ui.tabs_helpers",
    "ui.tabs_scan",
    "ui.tabs_network",
    "ui.tabs_diag",
    "ui.tabs_logger",
    "ui.tabs_analysis",
    "ui.tabs_recon",
    "ui.tabs_diag_extra",
    "ui.nav",
    "ui.nav.rail",
    "ui.nav.builder",
    "ui.monitor_state",
    "ui.plugin_page_mixin",
    "ui.command_palette",
    "ui.help",
    "ui.help_tab",
    "ui.app_settings",
    "ui.empty_state",
    "ui.expanding_table",
    "ui.first_run_dialog",
    "ui.live_graph",
    "ui.npcap_banner",
    "ui.skeleton",
    "ui.styles",
    "ui.system_tray",
    "ui.topology_widget",
    "ui.pages.network_map_page",
    "ui.pages.automation_page",
    "ui.pages.baseline_page",
    "ui.pages.cert_page",
    "ui.pages.connections_page",
    "ui.pages.cve_page",
    "ui.pages.dhcp_lease_page",
    "ui.pages.discover_page",
    "ui.pages.discover_data",
    "ui.pages.help_content",
    "ui.pages.home_suggestions",
    "ui.pages.home_data_mixin",
    "ui.pages.notif_extra_channels",
    "ui.pages.notif_alert_history",
    "ui.pages.notif_dep_card",
    "ui.pages.dns_zone_page",
    "ui.pages.geo_map_page",
    "ui.pages.history_page",
    "ui.pages.home_automation_page",
    "ui.pages.home_page",
    "ui.pages.inventory_page",
    "ui.pages.ip_calculator_page",
    "ui.pages.lab_mode_page",
    "ui.pages.app_traffic_page",
    "ui.pages.live_bandwidth_page",
    "ui.pages.log_hub_page",
    "ui.pages.log_source_panel",
    "ui.pages.maintenance_page",
    "ui.pages.mqtt_page",
    "ui.pages.network_doc_page",
    "ui.pages.notif_channel_panels",
    "ui.pages.notifications_page",
    "ui.pages.ookla_cli_banner",
    "ui.pages.overview_page",
    "ui.pages.protocol_viz_page",
    "ui.pages.reports_page",
    "ui.pages.service_diagnostics_page",
    "ui.pages.service_page",
    "ui.pages.settings_cards",
    "ui.pages.settings_page",
    "ui.pages.snmp_trap_page",
    "ui.pages.speed_test_page",
    "ui.pages.syslog_page",
    "ui.pages.threat_intel_page",
    "ui.pages.trend_page",
    "ui.pages.troubleshoot_page",
    "ui.pages.trigger_builder_page",
    "ui.pages.uptime_page",
    "ui.pages.wifi_heatmap_page",
    "ui.widgets.explainer_panel",
    "ui.widgets.protocol_canvas",
    "ui.widgets.signal_bar",
    "modules.protocol_animator",
    "modules.protocol_animator_extra",
    "modules.settings_io",
    "modules.digest_builder",
    "modules.geo_locator",
    "modules.automation_hooks",
    "modules.trigger_expression",
    "modules.mqtt_publisher",
    "modules.plugin_registry",
    "modules.web_dashboard",
    "modules.zte_client",
    "modules.net_doc_generator",
    "modules.exporter",
    # ── ui/pages/ missing from original list ──────────────────────────────────
    "ui.pages.diagnosis_page",
    "ui.pages.monitor_overview_page",
    "ui.pages.security_overview_page",
    "ui.pages.rest_api_page",
    "ui.pages.timeline_page",
    "ui.pages.plugin_device_page",
    "ui.pages.wifi_monitor_page",
    # ── ui/widgets/ — all widget modules ──────────────────────────────────────
    "ui.widgets.diagnostic_card_widget",
    "ui.widgets.alert_drawer",
    "ui.widgets.animated_kpi",
    "ui.widgets.coach_mark",
    "ui.widgets.context_menu",
    "ui.widgets.density_toggle",
    "ui.widgets.device_popover",
    "ui.widgets.device_detail_pane",
    "ui.widgets.device_detail_panels",
    "ui.widgets.inventory_dialogs",
    "ui.widgets.empty_state_card",
    "ui.widgets.home_widgets",
    "ui.widgets.home_session_widgets",
    "ui.widgets.jargon_tooltip",
    "ui.widgets.hub_card",
    "ui.widgets.hub_helpers",
    "ui.widgets.kpi_bar",
    "ui.widgets.modem_signal_panel",
    "ui.widgets.overview_tile",
    "ui.widgets.overview_tile_monitor",
    "ui.widgets.page_header",
    "ui.widgets.pulsing_dot",
    "ui.widgets.scan_summary_sheet",
    "ui.widgets.skeleton",
    "ui.widgets.toast",
    "ui.widgets.bandwidth_hog_card",
    "ui.widgets.usage_insights_card",
    "ui.widgets.weekly_report_card",
    "ui.widgets.quick_check_window",
    "ui.widgets.scan_radar_widget",
    # ── Scapy 802.11 layer (M9 — wifi_monitor_worker) ─────────────────────────
    "scapy.layers.dot11",
    # ── waitress WSGI server (REST API production backend) ────────────────────
    "waitress",
    "waitress.server",
    "waitress.task",
    # ── workers/ — all QThread workers ────────────────────────────────────────
    "workers.availability_worker",
    "workers.cert_worker",
    "workers.dhcp_lease_worker",
    "workers.diagnosis_worker",
    "workers.dns_zone_worker",
    "workers.ha_worker",
    "workers.app_traffic_worker",
    "workers.iface_bw_worker",
    "workers.process_worker",
    "workers.proactive_probe_worker",
    "workers.report_scheduler_worker",
    "workers.rest_api_worker",
    "workers.scan_worker",
    "workers.service_diagnostics_worker",
    "workers.service_worker",
    "workers.snmp_trap_worker",
    "workers.speed_test_worker",
    "workers.syslog_worker",
    "workers.threat_intel_worker",
    "workers.hw_detect_worker",
    "workers.plugin_polling_worker",
    "workers.plugin_worker",
    "workers.wifi_monitor_worker",
    "modules.passive_observer",
    "modules.lldp_scanner",
    "workers.passive_observer_worker",
    "workers.lldp_worker",
    "workers.health_worker",
    "workers.isp_vs_router_worker",
    "workers.bandwidth_worker",
    "ui.pages.hardware_integration_page",
    "ui.pages.plugin_guide",
    "ui.pages.plugin_wizard_mixin",
    "ui.pages.hardware_browse_mixin",
    "ui.widgets.credential_dialog",
]

for _pkg in ("scapy", "PyQt6", "matplotlib", "flask", "keyring"):
    _d, _b, _h = collect_all(_pkg)
    datas         += _d
    binaries      += _b
    hiddenimports += _h

# Collect WebEngine data files (pak resources, ICU data, qtwebengine_locales,
# QtWebEngineProcess binary).  These are not part of the base PyQt6 package so
# collect_all("PyQt6") alone does not pull them in.
for _pkg in ("PyQt6.QtWebEngineWidgets", "PyQt6.QtWebEngineCore", "PyQt6.QtWebChannel"):
    try:
        _d, _b, _h = collect_all(_pkg)
        datas         += _d
        binaries      += _b
        hiddenimports += _h
    except Exception:
        pass  # non-fatal — package absent in build env; interactive map falls back to Classic

# ── Analysis ──────────────────────────────────────────────────────────────────
a = Analysis(
    ["app.py"],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="NetSentinel",
    debug=_debug_build,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=_debug_build,              # False in production, True for debug
    disable_windowed_traceback=True,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="assets/icons/NetSentinel.ico" if sys.platform == "win32" else None,
)

# macOS: wrap the binary in a .app bundle (only relevant on macOS)
if sys.platform == "darwin":
    app = BUNDLE(  # noqa: F821 — PyInstaller injects this name at build time
        exe,
        name="NetSentinel.app",
        icon="assets/icons/NetSentinel.ico",
        bundle_identifier="com.netsentinel.app",
        info_plist={
            "NSHighResolutionCapable": True,
            "NSRequiresAquaSystemAppearance": False,
        },
    )
