"""
Diagnostic card widget — fixed-size QWidget for PNG / clipboard export.

render_card_widget(CardData) → QWidget (520×300)

Extracted from modules/diagnostic_card.py to keep modules/ free of PyQt6
imports (ARCH RULE 1).
"""
from __future__ import annotations

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QFrame, QHBoxLayout, QLabel, QVBoxLayout, QWidget

from ui.styles import (
    ACCENT, AMBER, BG_CARD, BG_DARK, BORDER, GREEN, RED,
    TEXT_PRIMARY, TEXT_SECONDARY,
)

from modules.diagnostic_card import CardData

_GRADE_COLOR = {
    "A": GREEN, "B": GREEN, "C": AMBER,
    "D": RED,   "F": RED,   "N/A": ACCENT,
}


def render_card_widget(card_data: CardData) -> QWidget:
    """Return a 520×300 QWidget styled as a share card.

    Call widget.grab() → QPixmap for PNG export or clipboard copy.
    """
    gc = _GRADE_COLOR.get(card_data.grade, ACCENT)

    card = QWidget()
    card.setFixedSize(520, 300)
    card.setStyleSheet(f"background:{BG_DARK};")

    root = QVBoxLayout(card)
    root.setContentsMargins(24, 20, 24, 16)
    root.setSpacing(0)

    # ── Grade circle + title block ────────────────────────────────────────
    top = QHBoxLayout()
    top.setSpacing(16)

    grade_lbl = QLabel(card_data.grade)
    grade_lbl.setFixedSize(72, 72)
    grade_lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
    grade_lbl.setStyleSheet(
        f"font-size:32px; font-weight:bold; color:{gc};"
        f" border:3px solid {gc}; border-radius:36px; background:{BG_CARD};"
    )

    info = QVBoxLayout()
    info.setSpacing(3)
    for text, style in [
        ("NetSentinel — Network Health Card",
         f"font-size:13px; font-weight:bold; color:{TEXT_PRIMARY}; background:transparent;"),
        (card_data.isp,
         f"font-size:11px; color:{TEXT_SECONDARY}; background:transparent;"),
        (f"Score {card_data.score:.0f}/100  ·  "
         f"{card_data.device_count} device(s)  ·  {card_data.generated_at}",
         f"font-size:10px; color:{TEXT_SECONDARY}; background:transparent;"),
    ]:
        lbl = QLabel(text)
        lbl.setStyleSheet(style)
        info.addWidget(lbl)

    top.addWidget(grade_lbl)
    top.addLayout(info, 1)
    root.addLayout(top)
    root.addSpacing(14)

    div = QFrame()
    div.setFrameShape(QFrame.Shape.HLine)
    div.setStyleSheet(f"color:{BORDER};")
    root.addWidget(div)
    root.addSpacing(10)

    # ── Findings ──────────────────────────────────────────────────────────
    for finding in card_data.findings:
        row = QHBoxLayout()
        row.setSpacing(8)
        dot = QLabel("·")
        dot.setFixedWidth(10)
        dot.setStyleSheet(f"color:{ACCENT}; background:transparent; font-size:14px;")
        txt = QLabel(finding)
        txt.setWordWrap(True)
        txt.setStyleSheet(f"font-size:11px; color:{TEXT_PRIMARY}; background:transparent;")
        row.addWidget(dot)
        row.addWidget(txt, 1)
        root.addLayout(row)
        root.addSpacing(3)

    root.addStretch()

    attr = QLabel(
        "Generated by NetSentinel — free at github.com/ossianericson/netsentinel"
    )
    attr.setStyleSheet(f"font-size:9px; color:{TEXT_SECONDARY}; background:transparent;")
    root.addWidget(attr)

    return card
