"""
hub_plugin_template.py — the _TEMPLATE string shown/generated by the
"Write a Plugin" guide and the "⬡ New Plugin" wizard.

Split out of hub_helpers.py (RULE-AH1-ENFORCE: file exceeded its LOC budget)
so the template's own docs/comments can stay complete without pressuring an
unrelated budget. hub_helpers.py re-exports _TEMPLATE for backward
compatibility with every existing importer (hub_card.py, plugin_guide.py,
plugin_wizard_mixin.py) — do not rename this constant.
"""
from __future__ import annotations

__all__ = ["_TEMPLATE"]

_TEMPLATE = '''\
"""
NetSentinel Hardware Integration Script
Hardware: <YOUR HARDWARE NAME>
Author:   <YOUR NAME>

Test this script standalone first:
    python this_file.py
    python this_file.py --netsentinel   (prints the exact JSON NetSentinel expects)

Once the output looks correct, import it via the
Hardware Integration page in NetSentinel.

Tip: search "<your model> local API" or "<your model> REST API"
     to find community docs for your specific hardware.

Requests must always pass timeout=10 (or similar) — an unreachable device
with no timeout blocks NetSentinel\'s polling thread instead of reporting
NET: quickly.
"""

import json
import sys

# ── Metadata (required) ───────────────────────────────────────────────────────
HARDWARE_NAME = "My Router XYZ"     # displayed in the app
HARDWARE_TYPE = "router"            # router | modem | ap | switch | other
HARDWARE_IP   = "192.168.1.1"       # your device\'s LAN address
USERNAME      = "admin"


# ── Optional: Typed configuration schema (P2-2) ───────────────────────────────
# Uncomment and fill in CONFIG_SCHEMA to enable the ⚙ Configure button in the
# Hub card.  The card auto-generates a settings panel; saved values are passed
# to get_status() as the keyword argument: get_status(config={"poll_interval": 60})
# get_status() must therefore accept a config kwarg (see below) even if you
# never uncomment this.
#
# CONFIG_SCHEMA = {
#     "poll_interval": {"type": "int",  "default": 60, "min": 10, "max": 600,
#                       "label": "Poll interval (s)"},
#     "verify_ssl":    {"type": "bool", "default": True,
#                       "label": "Verify SSL certificate"},
#     "base_url":      {"type": "str",  "default": "http://192.168.1.1",
#                       "label": "Device URL"},
# }


# ── Credentials (read from OS keychain — never hard-code passwords) ───────────

def _load_password() -> str:
    """Return the saved admin password from the OS keychain.

    The IP is resolved from the worker-injected globals() attribute first so
    multiple instances at different IPs each use the correct credential.
    Save the password using the Hardware Integration page in NetSentinel.
    """
    # globals() == this module\'s __dict__; PluginPollingWorker injects the IP here
    _ip = globals().get("_NETSENTINEL_INSTANCE_IP") or HARDWARE_IP
    try:
        import keyring
        _iid = globals().get("_NETSENTINEL_INSTANCE_ID") or ""
        pw = None
        if _iid:
            pw = keyring.get_password("NetSentinel/plugin", _iid)
        if not pw:
            pw = keyring.get_password("NetSentinel/hardware", _ip)
        if pw:
            return pw
    except Exception:
        pass  # keyring backend unavailable or OS error — caller's RuntimeError below explains the fix
    raise RuntimeError(
        f"No password saved for {_ip}. "
        "Enter and save the password in the Hardware Integration page."
    )


# ── Error classification (REQUIRED — do not skip) ─────────────────────────────
# get_status()/get_clients() must catch every exception and return it through
# extra.error via _fmt_err(), never let it propagate. An uncaught exception is
# reported as an UNCLASSIFIED error and wrongly counts toward the auto-disable
# circuit breaker even for a simple wrong password — see the prefixes below.

def _fmt_err(exc: Exception) -> str:
    """Return a structured error string with a machine-readable prefix.

    DEPS: — missing pip package (ImportError, or message contains "pip install")
    NET:  — device unreachable / connection refused / timed out
    AUTH: — wrong credentials
    ERR:  — anything else

    Classified by exception type / HTTP status code FIRST, falling back to
    message keywords only when neither is available: a raw requests
    ConnectionError\'s message includes the request URL, so if that URL\'s path
    happens to contain a word like "login" (e.g. POST /api/login), naive
    keyword-only matching misclassifies a plain connection failure as AUTH:.
    Checking the exception type name (Connection/Timeout) and, for requests\'
    HTTPError, response.status_code (401/403) avoids that trap. If you use
    urllib instead of requests: urllib.error.HTTPError has .code (not
    .response.status_code), and urllib.error.URLError wraps the real socket
    exception in .reason — both are checked too, so this works either way.
    Fall back to keyword matching for libraries that raise their own
    descriptive exception classes with no .response/.code/.reason attribute
    (message text is checked for network keywords BEFORE auth keywords: a
    timeout during login must classify as NET, not AUTH).

    AUTH: errors do NOT count toward the auto-disable circuit breaker (a wrong
    password won\'t fix itself by retrying); NET:/ERR: do.
    """
    msg = str(exc)
    if isinstance(exc, ImportError) or "pip install" in msg:
        return "DEPS: " + msg
    type_name = type(exc).__name__
    status = getattr(getattr(exc, "response", None), "status_code", None)
    if status in (401, 403):
        return "AUTH: " + msg
    if getattr(exc, "code", None) in (401, 403):  # urllib.error.HTTPError
        return "AUTH: " + msg
    if any(w in type_name for w in ("Connection", "Timeout")):
        return "NET: " + msg
    reason = getattr(exc, "reason", None)  # urllib.error.URLError wraps the real cause
    if reason is not None and any(w in type(reason).__name__ for w in ("Connection", "Timeout")):
        return "NET: " + msg
    lm = msg.lower()
    if any(w in lm for w in ("refused", "timed out", "unreachable", "no route", "network is")):
        return "NET: " + msg
    if any(w in lm for w in ("auth", "password", "login", "401", "forbidden", "wrong credential")):
        return "AUTH: " + msg
    return "ERR: " + msg


# ── Required interface ────────────────────────────────────────────────────────

def get_info() -> dict:
    """Static metadata — called once when the script is first imported."""
    return {
        "name":         HARDWARE_NAME,
        "type":         HARDWARE_TYPE,
        "ip":           HARDWARE_IP,
        "manufacturer": "Brand Name",
        "model":        "XYZ-1000",
        "firmware":     "v1.0.0",       # fetch from device API or hardcode
    }


def get_status(config=None) -> dict:
    """Live status — called periodically when the page is visible.

    config               — present only if CONFIG_SCHEMA is defined above;
                            accept it even if unused (see CONFIG_SCHEMA note).
    connected_clients    — total connected client count (shown on Overview tile)
    extra.nodes          — list of node dicts; drives topology mid-layer and
                           the "Group by node" button in the Devices table.
                           For a single router: one entry with role="primary".
                           Each node needs at least: name, mac, ip, role.
    extra.error          — set ONLY on failure via _fmt_err() above; omit or
                           leave falsy on success.
    """
    try:
        # TODO: replace with your hardware\'s real API calls, e.g.:
        #   pw = _load_password()
        #   resp = requests.get(f"http://{HARDWARE_IP}/api/status",
        #                       auth=(USERNAME, pw), timeout=10)
        #   resp.raise_for_status()
        return {
            "wan_ip":            None,      # WAN/public IP if available
            "uptime_sec":        None,      # router uptime in seconds
            "download_mbps":     None,
            "upload_mbps":       None,
            "signal_dbm":        None,
            "connected_clients": 0,
            "mesh_nodes":        1,
            "extra": {
                "nodes": [
                    # For a single router use one entry like this:
                    {"name": HARDWARE_NAME, "mac": "", "ip": HARDWARE_IP, "role": "primary"},
                ],
            },
        }
    except Exception as exc:
        return {
            "wan_ip": None, "uptime_sec": None,
            "download_mbps": None, "upload_mbps": None,
            "signal_dbm": None, "connected_clients": None,
            "extra": {"error": _fmt_err(exc)},
        }


# ── Optional interface ────────────────────────────────────────────────────────

def get_clients() -> list:
    """Return connected devices.

    unit  — name of the mesh node / AP this device is connected to.
             Populates the "Node" column in the Devices table and enables
             the "Group by node" button. For a single router use HARDWARE_NAME.
    band  — Wi-Fi band string, e.g. "2.4G", "5G", "6G", "Wired".
    """
    try:
        return []  # TODO: [{"ip": ..., "mac": ..., "hostname": ..., "unit": HARDWARE_NAME, "band": "5G"}, ...]
    except Exception:
        return []  # get_clients() failures are non-fatal — return empty, not an error


# ── Standalone test ───────────────────────────────────────────────────────────
if __name__ == "__main__" and "--netsentinel" not in sys.argv:
    print("=== Hardware Info ===")
    print(json.dumps(get_info(), indent=2, default=str))
    print("\\n=== Live Status ===")
    print(json.dumps(get_status(), indent=2, default=str))
    print("\\n=== Clients ===")
    print(json.dumps(get_clients(), indent=2, default=str))

# ── NetSentinel plugin shim (manual standalone test hook — do not remove) ─────
# NOT called by the running app: NetSentinel loads plugins in-process and
# calls get_info()/get_status()/get_clients() directly (see
# workers/plugin_polling_worker.py). This shim only serves
# `python this_file.py --netsentinel` so you can preview the exact JSON shape
# before importing the plugin into the app.
import sys as _sys
if "--netsentinel" in _sys.argv:
    import json as _json
    try:
        _clients = get_clients()
    except NameError:
        _clients = []
    _sys.stdout.write(_json.dumps({
        "info":    get_info(),
        "status":  get_status(),
        "clients": _clients,
    }, default=str) + "\\n")
    _sys.exit(0)
'''
