"""One-shot script: reorganise Standard nav section in dashboard.py."""
import pathlib

src_path = pathlib.Path("ui/dashboard.py")
src = src_path.read_text(encoding="utf-8")

new_standard = (
    "        # \u2500\u2500 STANDARD (expanded by default)"
    " \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500"
    "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500"
    "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500"
    "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500"
    "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "        self._nav_add_section(\"Standard\", icon=\"\u25fc\")\n"
    "        # Overview is always first \u2014 orientation / live dashboard\n"
    "        self._nav_add_page(\"\U0001f3e0\", \"Overview\",             self._overview_page)\n"
    "\n"
    "        # Discover \u2014 what is on the network (first thing a new user needs)\n"
    "        self._nav_add_subgroup(\"Discover\", icon=\"\U0001f5a5\")\n"
    "        self._nav_add_page(\"\U0001f5a5\",  \"Devices on Network\",  m1)\n"
    "        self._nav_add_page(\"\U0001f310\", \"WiFi Networks\",        m4)\n"
    "        self._nav_add_page(\"\u2139\",  \"Network Info\",         net)\n"
    "        self._nav_current_subgroup = -1\n"
    "\n"
    "        # Live Monitor \u2014 what is happening right now\n"
    "        self._nav_add_subgroup(\"Live Monitor\", icon=\"\U0001f4f6\")\n"
    "        self._nav_add_page(\"\U0001f517\", \"Active Connections\",   self._connections_page)\n"
    "        self._nav_add_page(\"\U0001f4f6\", \"Live Bandwidth\",       self._live_bandwidth_page)\n"
    "        self._nav_add_page(\"\U0001f4e1\", \"DNS " + chr(38) + " Outages\",        m5)\n"
    "        self._nav_current_subgroup = -1\n"
    "\n"
    "        # Threat Detection \u2014 the core differentiator; must be prominent\n"
    "        self._nav_add_subgroup(\"Threat Detection\", icon=\"\U0001f6e1\")\n"
    "        self._nav_add_page(\"\U0001f32a\", \"Broadcast Storm\",      m3)\n"
    "        self._nav_add_page(\"\U0001f500\", \"Rogue Bridge (STP)\",   m2)\n"
    "        self._nav_add_page(\"\U0001f916\", \"IoT Behaviour\",        self._iot_baseline_tab_widget)\n"
    "        self._nav_current_subgroup = -1\n"
    "\n"
    "        # Health " + chr(38) + " History \u2014 monitoring over time\n"
    "        self._nav_add_subgroup(\"Health " + chr(38) + " History\", icon=\"\U0001f4ca\")\n"
    "        self._nav_add_page(\"\U0001f5d3\", \"Availability History\", self._history_page)\n"
    "        self._nav_add_page(\"\U0001f4dc\", \"Inventory Changes\",    self._inventory_page)\n"
    "        self._nav_add_page(\"\u2705\", \"Uptime " + chr(38) + " SLA\",         self._uptime_page)\n"
    "        self._nav_add_page(\"\U0001f50c\", \"Service Heartbeat\",    self._service_page)\n"
    "        self._nav_add_page(\"\U0001f4ca\", \"Network Grade\",        self._benchmark_tab_widget)\n"
    "        self._nav_current_subgroup = -1\n"
    "\n"
    "        # Diagnostics \u2014 deeper investigation\n"
    "        self._nav_add_subgroup(\"Diagnostics\", icon=\"\U0001f48a\")\n"
    "        self._nav_add_page(\"\U0001f48a\", \"Health Check\",         dia)\n"
    "        self._nav_add_page(\"\U0001f4cb\", \"Stability Log\",        log)\n"
    "        self._nav_add_page(\"\U0001f50d\", \"Root Cause Analysis\",  self._correlator_tab_widget)\n"
    "        self._nav_add_page(\"\U0001f4c8\", \"Trend Forecasts\",      self._trend_page)\n"
    "        self._nav_add_page(\"\U0001f537\", \"IPv6 Devices\",         self._ipv6_tab_widget)\n"
    "        self._nav_current_subgroup = -1\n"
    "\n"
    "        # Reports " + chr(38) + " Alerts \u2014 config and admin\n"
    "        self._nav_add_subgroup(\"Reports " + chr(38) + " Alerts\", icon=\"\U0001f514\")\n"
    "        self._nav_add_page(\"\U0001f514\", \"Notifications\",        self._notifications_page)\n"
    "        self._nav_add_page(\"\U0001f4c4\", \"Auto Reports\",         self._reports_page)\n"
    "        self._nav_add_page(\"\U0001f4f8\", \"Config Snapshots\",     self._baseline_page)\n"
    "        self._nav_add_page(\"\U0001f527\", \"Maintenance Windows\",  self._maintenance_page)\n"
    "        self._nav_current_subgroup = -1\n"
    "\n"
    "        # Tools \u2014 utilities not tied to continuous monitoring\n"
    "        self._nav_add_subgroup(\"Tools\", icon=\"\u26a1\")\n"
    "        self._nav_add_page(\"\u26a1\", \"Speed Test\",           self._speed_test_page)\n"
    "        self._nav_add_page(\"\U0001f3e1\", \"Home Automation\",      self._ha_page)\n"
    "        self._nav_current_subgroup = -1\n"
    "\n"
)

STANDARD_MARKER = "        # \u2500\u2500 STANDARD (expanded by default)"
ADVANCED_MARKER = "        # \u2500\u2500 ADVANCED (collapsed by default)"

start = src.find(STANDARD_MARKER)
end   = src.find(ADVANCED_MARKER)
assert start != -1, "STANDARD marker not found"
assert end   != -1, "ADVANCED marker not found"

new_src = src[:start] + new_standard + src[end:]
src_path.write_text(new_src, encoding="utf-8")
print(f"Done. Replaced {end - start} bytes with {len(new_standard)} bytes.")
